name: ROS2 Test

on: 
  push:
    branches:
      - main
  pull_request:

jobs:
  test:
    runs-on: ubuntu-22.04

    steps:
      - uses: actions/checkout@v3

      - name: Set up ROS2 environment
        run: |
          sudo apt update
          sudo apt install -y python3-colcon-common-extensions ros-humble-desktop
          source /opt/ros/humble/setup.bash

      - name: Prepare workspace
        run: |
          mkdir -p ~/ros2_ws/src
          rsync -av . ~/ros2_ws/src/mypkg/

      - name: Build and Test
        run: |
          chmod +x ~/ros2_ws/src/mypkg/test/test.bash
          ~/ros2_ws/src/mypkg/test/test.bash ~

